# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Siyi Wang
title: Human
email: wangsi22@msu.edu
website: https://github.com/SeeWang

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: facespics
github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jameswgrant
linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/mycat.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi there, I'm a university student who's majoring in procrastination with a minor in binge-watching random documentaries at 2am. While I could be building the next big thing in tech, I’m instead perfecting the art of wasting time in increasingly creative ways. When I'm not stressing about deadlines I ignored two weeks ago, I'm usually staring at my cat, who now proudly represents me as my profile picture.

  I am most skilled in: <mark>Putting things off</mark>, <mark>Making instant noodles look gourmet</mark> and <mark>Taking aesthetic pictures of my cat</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Sort-of Useful Project
        link: github.com/SeeWang/maybe-this-works
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/SeeWang
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          It might not be revolutionary, but at least it didn't crash (too often).
        description: | # this will include new lines to allow paragraphs
          This project started as a distraction and somehow turned into something that almost looks like a real app. I'm still not sure how it works entirely, but it does things and sometimes that's enough. It's far from perfect, but I've learned a lot through the chaos.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Professional Time-Waster
        link: https://seewang.github.io/
        # link_text: boringcompany.com
        sub_title: Full-time Procrastinator
        caption: Feb 2003 - Present
        quote: >
          Still waiting to be discovered for my true potential: napping and doomscrolling.
        description: | # this will include new lines to allow paragraphs
            Responsibilities include:

            · Avoiding deadlines with unparalleled skill

            · Staring at VSCode for hours while doing nothing

            · Managing an emotional support cat during stressful times (she does more work than I do)

            · Accidentally learning things while trying not to



  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Not-Harvard University
        caption: 2022 - Ongoing
        sub_title: BS in Surviving Group Projects
        quote: >
          Somewhere between sleep and panic.
        description: | # this will include new lines to allow paragraphs
          I've mastered the art of last-minute submissions and the strategic nap.
          Courses I excelled in:

          · Intro to "This Wasn't on the Slides"

          · Advanced Snack Acquisition

          · Discrete Sadness (a.k.a. C++)

          · Currently writing a thesis on: "How I Somehow Keep Passing Without Understanding Anything."

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I'm not busy pretending to be productive, I spend time exploring random hobbies, making suspiciously specific playlists, and overthinking everything.
      I recently uploaded something weirdly personal but maybe kind of cool — check it out below:

      [This video changed my GPA forever (not clickbait)](https://www.youtube.com/watch?v=dQw4w9WgXcQ)


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
